// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/tiptok/gopp/pkg/domain"
)

type ListUser struct {
	Total int             `json:"total"`
	Users []*domain.Users `json:"users"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Role struct {
	ID       *int    `json:"id"`
	RoleName *string `json:"roleName"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}
