// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitDb(dns string) (DB, error) {
	dbConfig := NewDbConfig(dns)
	db := NewPostgresqlDB(dbConfig)
	return db, nil
}

func InjectFooBar() FooBar {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBar := FooBar{
		MyFoo: foo,
		MyBar: bar,
	}
	return fooBar
}
